#!/usr/bin/env python
import boto3
from serverless_utils.aws.stack import stack_output


STACK_NAME = 'itay-test-stack'
sqs = boto3.resource('sqs')

queue1 = sqs.Queue(stack_output(STACK_NAME, 'Queue1Url'))
queue1.send_message(
    MessageBody='some content',
    MessageSystemAttributes={
        'AWSTraceHeader': {
            'StringValue': '2-5f8988da-2e8079fd5363818366eb0188',
            'DataType': 'String',
        }
    }
)
